name = "sso-serverless"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# Environment variables (secrets)
# Use: wrangler secret put DISQUS_SECRET_KEY
# Use: wrangler secret put DISQUS_PUBLIC_KEY
#
# For local development, create a .dev.vars file with:
# DISQUS_SECRET_KEY=your_secret_key
# DISQUS_PUBLIC_KEY=your_public_key
