name: Deploy Frontends to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/frontend-vanilla/**'
      - 'packages/frontend-react/**'
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies for React frontend
        run: |
          cd packages/frontend-react
          npm install
          
      - name: Build React frontend
        run: |
          cd packages/frontend-react
          npm run build
          
      - name: Create deployment directory
        run: |
          mkdir -p deploy-site
          
      - name: Copy vanilla frontend
        run: |
          mkdir -p deploy-site/vanilla
          cp -r packages/frontend-vanilla/* deploy-site/vanilla/
          
      - name: Copy React frontend build
        run: |
          mkdir -p deploy-site/react
          cp -r packages/frontend-react/dist/* deploy-site/react/
          
      - name: Copy landing page
        run: |
          cp index.html deploy-site/
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy-site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
